/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SeatingRouteImport } from './routes/seating'
import { Route as NfcRouteImport } from './routes/nfc'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FoodRouteImport } from './routes/food'
import { Route as CrowdRouteImport } from './routes/crowd'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiLiveWeatherRouteImport } from './routes/api/live/weather'
import { Route as ApiLiveSocketRouteImport } from './routes/api/live/socket'
import { Route as ApiLiveCrowdRouteImport } from './routes/api/live/crowd'
import { Route as ApiLiveAlertsRouteImport } from './routes/api/live/alerts'

const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatingRoute = SeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcRoute = NfcRouteImport.update({
  id: '/nfc',
  path: '/nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdRoute = CrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiLiveWeatherRoute = ApiLiveWeatherRouteImport.update({
  id: '/api/live/weather',
  path: '/api/live/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSocketRoute = ApiLiveSocketRouteImport.update({
  id: '/api/live/socket',
  path: '/api/live/socket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveCrowdRoute = ApiLiveCrowdRouteImport.update({
  id: '/api/live/crowd',
  path: '/api/live/crowd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveAlertsRoute = ApiLiveAlertsRouteImport.update({
  id: '/api/live/alerts',
  path: '/api/live/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/crowd': typeof CrowdRoute
  '/food': typeof FoodRoute
  '/leaderboard': typeof LeaderboardRoute
  '/nfc': typeof NfcRoute
  '/seating': typeof SeatingRoute
  '/sos': typeof SosRoute
  '/translate': typeof TranslateRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/live/alerts': typeof ApiLiveAlertsRoute
  '/api/live/crowd': typeof ApiLiveCrowdRoute
  '/api/live/socket': typeof ApiLiveSocketRoute
  '/api/live/weather': typeof ApiLiveWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/crowd': typeof CrowdRoute
  '/food': typeof FoodRoute
  '/leaderboard': typeof LeaderboardRoute
  '/nfc': typeof NfcRoute
  '/seating': typeof SeatingRoute
  '/sos': typeof SosRoute
  '/translate': typeof TranslateRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/live/alerts': typeof ApiLiveAlertsRoute
  '/api/live/crowd': typeof ApiLiveCrowdRoute
  '/api/live/socket': typeof ApiLiveSocketRoute
  '/api/live/weather': typeof ApiLiveWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/crowd': typeof CrowdRoute
  '/food': typeof FoodRoute
  '/leaderboard': typeof LeaderboardRoute
  '/nfc': typeof NfcRoute
  '/seating': typeof SeatingRoute
  '/sos': typeof SosRoute
  '/translate': typeof TranslateRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/live/alerts': typeof ApiLiveAlertsRoute
  '/api/live/crowd': typeof ApiLiveCrowdRoute
  '/api/live/socket': typeof ApiLiveSocketRoute
  '/api/live/weather': typeof ApiLiveWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/auth'
    | '/crowd'
    | '/food'
    | '/leaderboard'
    | '/nfc'
    | '/seating'
    | '/sos'
    | '/translate'
    | '/admin'
    | '/api/live/alerts'
    | '/api/live/crowd'
    | '/api/live/socket'
    | '/api/live/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/auth'
    | '/crowd'
    | '/food'
    | '/leaderboard'
    | '/nfc'
    | '/seating'
    | '/sos'
    | '/translate'
    | '/admin'
    | '/api/live/alerts'
    | '/api/live/crowd'
    | '/api/live/socket'
    | '/api/live/weather'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alerts'
    | '/assistant'
    | '/auth'
    | '/crowd'
    | '/food'
    | '/leaderboard'
    | '/nfc'
    | '/seating'
    | '/sos'
    | '/translate'
    | '/_authenticated/admin'
    | '/api/live/alerts'
    | '/api/live/crowd'
    | '/api/live/socket'
    | '/api/live/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CrowdRoute: typeof CrowdRoute
  FoodRoute: typeof FoodRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NfcRoute: typeof NfcRoute
  SeatingRoute: typeof SeatingRoute
  SosRoute: typeof SosRoute
  TranslateRoute: typeof TranslateRoute
  ApiLiveAlertsRoute: typeof ApiLiveAlertsRoute
  ApiLiveCrowdRoute: typeof ApiLiveCrowdRoute
  ApiLiveSocketRoute: typeof ApiLiveSocketRoute
  ApiLiveWeatherRoute: typeof ApiLiveWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seating': {
      id: '/seating'
      path: '/seating'
      fullPath: '/seating'
      preLoaderRoute: typeof SeatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc': {
      id: '/nfc'
      path: '/nfc'
      fullPath: '/nfc'
      preLoaderRoute: typeof NfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowd': {
      id: '/crowd'
      path: '/crowd'
      fullPath: '/crowd'
      preLoaderRoute: typeof CrowdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/live/weather': {
      id: '/api/live/weather'
      path: '/api/live/weather'
      fullPath: '/api/live/weather'
      preLoaderRoute: typeof ApiLiveWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/socket': {
      id: '/api/live/socket'
      path: '/api/live/socket'
      fullPath: '/api/live/socket'
      preLoaderRoute: typeof ApiLiveSocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/crowd': {
      id: '/api/live/crowd'
      path: '/api/live/crowd'
      fullPath: '/api/live/crowd'
      preLoaderRoute: typeof ApiLiveCrowdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/alerts': {
      id: '/api/live/alerts'
      path: '/api/live/alerts'
      fullPath: '/api/live/alerts'
      preLoaderRoute: typeof ApiLiveAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CrowdRoute: CrowdRoute,
  FoodRoute: FoodRoute,
  LeaderboardRoute: LeaderboardRoute,
  NfcRoute: NfcRoute,
  SeatingRoute: SeatingRoute,
  SosRoute: SosRoute,
  TranslateRoute: TranslateRoute,
  ApiLiveAlertsRoute: ApiLiveAlertsRoute,
  ApiLiveCrowdRoute: ApiLiveCrowdRoute,
  ApiLiveSocketRoute: ApiLiveSocketRoute,
  ApiLiveWeatherRoute: ApiLiveWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
